### ISSUE TITLE
Unable to build react because of failed nuget dependencies

### ISSUE THREAD

**Issue by antogg2004** [jasontaylordev/CleanArchitecture#983] opened 2023-09-01 07:53 UTC
The current code from git does not build because of broken dependencies - the solution was created with

dotnet new ca-sln -cf React -o DarkMatterCms

The restore outputs this:

PS C:\dev\Personal\DarkMatterCms\Net8.0\DarkMatterCms> dotnet restore
  Determining projects to restore...
C:\dev\Personal\DarkMatterCms\Net8.0\DarkMatterCms\src\Application\Application.csproj : error NU1603: Warning As Error: FluentValidation.DependencyInjectionExtensions 11.6.0 depends on FluentValidation (>= 11.6.0) but FluentValidation 11.6.0 was not found. An approximat
e best match of FluentValidation 11.7.0 was resolved. [C:\dev\Personal\DarkMatterCms\Net8.0\DarkMatterCms\DarkMatterCms.sln]
C:\dev\Personal\DarkMatterCms\Net8.0\DarkMatterCms\src\Infrastructure\Infrastructure.csproj : error NU1603: Warning As Error: FluentValidation.DependencyInjectionExtensions 11.6.0 depends on FluentValidation (>= 11.6.0) but FluentValidation 11.6.0 was not found. An appr
oximate best match of FluentValidation 11.7.0 was resolved. [C:\dev\Personal\DarkMatterCms\Net8.0\DarkMatterCms\DarkMatterCms.sln]
C:\dev\Personal\DarkMatterCms\Net8.0\DarkMatterCms\tests\Application.UnitTests\Application.UnitTests.csproj : error NU1603: Warning As Error: FluentValidation.DependencyInjectionExtensions 11.6.0 depends on FluentValidation (>= 11.6.0) but FluentValidation 11.6.0 was no
t found. An approximate best match of FluentValidation 11.7.0 was resolved. [C:\dev\Personal\DarkMatterCms\Net8.0\DarkMatterCms\DarkMatterCms.sln]
C:\dev\Personal\DarkMatterCms\Net8.0\DarkMatterCms\tests\Web.AcceptanceTests\Web.AcceptanceTests.csproj : error NU1603: Warning As Error: SpecFlow.Plus.LivingDocPlugin 3.9.57 depends on SpecFlow (>= 3.9.8 && < 3.10.0) but SpecFlow 3.9.8 was not found. An approximate bes
t match of SpecFlow 3.9.58 was resolved. [C:\dev\Personal\DarkMatterCms\Net8.0\DarkMatterCms\DarkMatterCms.sln]
C:\dev\Personal\DarkMatterCms\Net8.0\DarkMatterCms\src\Web\Web.csproj : error NU1603: Warning As Error: FluentValidation.AspNetCore 11.3.0 depends on FluentValidation (>= 11.5.1) but FluentValidation 11.5.1 was not found. An approximate best match of FluentValidation 11
.7.0 was resolved. [C:\dev\Personal\DarkMatterCms\Net8.0\DarkMatterCms\DarkMatterCms.sln]
C:\dev\Personal\DarkMatterCms\Net8.0\DarkMatterCms\src\Web\Web.csproj : error NU1603: Warning As Error: FluentValidation.DependencyInjectionExtensions 11.6.0 depends on FluentValidation (>= 11.6.0) but FluentValidation 11.6.0 was not found. An approximate best match of
FluentValidation 11.7.0 was resolved. [C:\dev\Personal\DarkMatterCms\Net8.0\DarkMatterCms\DarkMatterCms.sln]
C:\dev\Personal\DarkMatterCms\Net8.0\DarkMatterCms\src\Web\Web.csproj : error NU1603: Warning As Error: ZymLabs.NSwag.FluentValidation.AspNetCore 0.6.2 depends on FluentValidation (>= 10.2.3) but FluentValidation 10.2.3 was not found. An approximate best match of Fluent
Validation 11.7.0 was resolved. [C:\dev\Personal\DarkMatterCms\Net8.0\DarkMatterCms\DarkMatterCms.sln]
C:\dev\Personal\DarkMatterCms\Net8.0\DarkMatterCms\tests\Application.FunctionalTests\Application.FunctionalTests.csproj : error NU1603: Warning As Error: FluentValidation.AspNetCore 11.3.0 depends on FluentValidation (>= 11.5.1) but FluentValidation 11.5.1 was not found
. An approximate best match of FluentValidation 11.7.0 was resolved. [C:\dev\Personal\DarkMatterCms\Net8.0\DarkMatterCms\DarkMatterCms.sln]
C:\dev\Personal\DarkMatterCms\Net8.0\DarkMatterCms\tests\Application.FunctionalTests\Application.FunctionalTests.csproj : error NU1603: Warning As Error: FluentValidation.DependencyInjectionExtensions 11.6.0 depends on FluentValidation (>= 11.6.0) but FluentValidation 1
1.6.0 was not found. An approximate best match of FluentValidation 11.7.0 was resolved. [C:\dev\Personal\DarkMatterCms\Net8.0\DarkMatterCms\DarkMatterCms.sln]
C:\dev\Personal\DarkMatterCms\Net8.0\DarkMatterCms\tests\Application.FunctionalTests\Application.FunctionalTests.csproj : error NU1603: Warning As Error: ZymLabs.NSwag.FluentValidation.AspNetCore 0.6.2 depends on FluentValidation (>= 10.2.3) but FluentValidation 10.2.3
was not found. An approximate best match of FluentValidation 11.7.0 was resolved. [C:\dev\Personal\DarkMatterCms\Net8.0\DarkMatterCms\DarkMatterCms.sln]
C:\dev\Personal\DarkMatterCms\Net8.0\DarkMatterCms\tests\Application.FunctionalTests\Application.FunctionalTests.csproj : error NU1100: Unable to resolve 'Testcontainers (>= 3.3.0)' for 'net8.0'. PackageSourceMapping is enabled, the following source(s) were not consider
ed: C:\Program Files\dotnet\library-packs, Microsoft Visual Studio Offline Packages, nuget.org. [C:\dev\Personal\DarkMatterCms\Net8.0\DarkMatterCms\DarkMatterCms.sln]
  Failed to restore C:\dev\Personal\DarkMatterCms\Net8.0\DarkMatterCms\src\Application\Application.csproj (in 330 ms).
  Restored C:\dev\Personal\DarkMatterCms\Net8.0\DarkMatterCms\tests\Infrastructure.IntegrationTests\Infrastructure.IntegrationTests.csproj (in 330 ms).
  Restored C:\dev\Personal\DarkMatterCms\Net8.0\DarkMatterCms\tests\Domain.UnitTests\Domain.UnitTests.csproj (in 330 ms).
  Failed to restore C:\dev\Personal\DarkMatterCms\Net8.0\DarkMatterCms\src\Infrastructure\Infrastructure.csproj (in 341 ms).
  Failed to restore C:\dev\Personal\DarkMatterCms\Net8.0\DarkMatterCms\src\Web\Web.csproj (in 355 ms).
  Failed to restore C:\dev\Personal\DarkMatterCms\Net8.0\DarkMatterCms\tests\Application.UnitTests\Application.UnitTests.csproj (in 350 ms).
  Failed to restore C:\dev\Personal\DarkMatterCms\Net8.0\DarkMatterCms\tests\Web.AcceptanceTests\Web.AcceptanceTests.csproj (in 354 ms).
  Failed to restore C:\dev\Personal\DarkMatterCms\Net8.0\DarkMatterCms\tests\Application.FunctionalTests\Application.FunctionalTests.csproj (in 343 ms).
  1 of 9 projects are up-to-date for restore.

**Comment by jasontaylordev** [comment] 2023-11-22 23:02
Apologies that it took me so long to get to this issue. I've done some testing on my side and while I did find and resolve an issue (#1057), I could not reproduce the above issue. If you wait 20 minutes, grab the latest template (I'm preparing it now), and try again, hopefully, you will find the issue resolved.

I'll close this one, but feel free to shout out if you reencounter it.

**Closed by jasontaylordev** 2023-11-22 23:02 UTC
