### ISSUE TITLE
NSwag and Client generating

### ISSUE THREAD

**Issue by sk0gen** [jasontaylordev/CleanArchitecture#131] opened 2020-05-09 15:57 UTC
So I had trouble generating client on linux, because there was no clear way how to do this.
I found [nswagNPM](https://www.npmjs.com/package/nswag) package and finally generated api-client.

My suggestion is write a script to generate client from specification (or directly from nswag.json, because it's well configured)

**Comment by michalkrzych** [comment] 2020-05-10 22:19
https://github.com/RicoSuter/NSwag/issues/2444

**Comment by michalkrzych** [comment] 2020-05-10 22:52
https://github.com/RicoSuter/NSwag/issues/2444

**Comment by michalkrzych** [comment] 2020-05-10 22:56
Duplicate of https://github.com/RicoSuter/NSwag/issues/2444

**Closed** 2020-05-17 20:55 UTC
