### ISSUE TITLE
The template project failed to start npm, though npm is in PATH

### ISSUE THREAD

**Issue by grassit** [jasontaylordev/CleanArchitecture#51] opened 2020-01-16 18:40 UTC
I try to build and run the  default project created from  [https://github.com/JasonGT/CleanArchitecture](https://github.com/JasonGT/CleanArchitecture) in .NET Core 3.1.100 in Ubuntu.

(1) It has a project for each layer. However, it doesn't ask me to explicitly build the other projects than the webUI project, according to these two steps:

* Run `dotnet new ca-sln`  to create a new project
* Navigate to src/WebUI  and run `dotnet run`  to launch the project

Is it true that when a project is being built, are all its dependency projects automatically built?

(2) When I run it as described above, and connect to [https://localhost:5001/](https://localhost:5001/) from web browser

>{"error":"One or more errors occurred. (One or more errors occurred. (Failed to start 'npm'. To resolve this:.\\n\\n\[1\] Ensure that 'npm' is installed and can be found in one of the PATH directories.\\n    Current PATH enviroment variable is: /home/t/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/t/.dotnet/tools:/opt/mssql-tools/bin\\n    Make sure the executable is in one of those directories, or update your PATH.\\n\\n\[2\] See the InnerException for further details of the cause.))"}

My npm is installed in `/usr/bin/npm`, which is in my `PATH`. I can start npm from shell without problem. So why do I have the problem that npm is not resolved and  how could I solve the problem?

Thanks.

**Comment by NhatTanVu** [comment] 2020-01-24 00:17
Hi grassit,

Can you show us the InnerException mentioned above?
Furthermore, seems that it's a known [issue](https://github.com/dotnet/aspnetcore/issues/18201) in VS 2019 v16.4.1

Hope it helps.

**Comment by Sekin** [comment] 2020-01-24 09:04
I can also use npm on the command line. However, VS Code shows me the following inner exception. I used the Debug and Run button to launch the program.

`System.AggregateException: One or more errors occurred. (One or more errors occurred. (Failed to start 'npm'. To resolve this:.`

[1] Ensure that 'npm' is installed and can be found in one of the PATH directories.
    Current PATH enviroment variable is: C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\LINQPad6;C:\Program Files\nodejs\;C:\Program Files\Terraform;C:\Users\sekin\AppData\Local\Microsoft\WindowsApps;C:\Users\sekin\.dotnet\tools;C:\Users\sekin\AppData\Roaming\npm
    Make sure the executable is in one of those directories, or update your PATH.

`[2] See the InnerException for further details of the cause.))
 ---> System.AggregateException: One or more errors occurred. (Failed to start 'npm'. To resolve this:.`

`[2] See the InnerException for further details of the cause.)
 ---> System.InvalidOperationException: Failed to start 'npm'. To resolve this:.`

`[2] See the InnerException for further details of the cause.
 ---> System.ComponentModel.Win32Exception (267): The directory name is invalid.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Microsoft.AspNetCore.NodeServices.Npm.NpmScriptRunner.LaunchNodeProcess(ProcessStartInfo startInfo)
   --- End of inner exception stack trace ---`
There was more. But I hope this helps.

**Comment by jasontaylordev** [comment] 2020-02-10 10:43
Sorry for the difficulties. I am not sure if you still need help, but if so - let me know. If I don't hear from you I'll assume it is sorted, and close this issue in a few days. Thanks.

**Closed** 2020-03-23 10:57 UTC
