### ISSUE TITLE
Creating a WebApi only the solution file has the incorrect project

### ISSUE THREAD

**Issue by Kyle-SenkevichPAR** [jasontaylordev/CleanArchitecture#901] opened 2023-07-07 18:16 UTC
**Describe the bug**
Using the provided command for generating a WebApi project in the generated solution it is missing the WebApi project and instead has a non existent WebUI project.  This is using the latest tool Clean.Architecture.Solution.Template::8.0.0-preview.5.5

`dotnet new ca-sln -cf None -o YourProjectName`

**Expected behavior**
The generated solution should include the WebApi project and not the WebUI

**Comment by jasontaylordev** [comment] 2023-07-07 22:29
Hi @Kyle-SenkevichPAR, thanks for reporting, however I cannot reproduce this issue. Please try the following.

Ensure you are running the latest .NET 8 SDK:
```bash
dotnet --version
```

It should be 8.0.100-preview.5.23303.2 or newer.

Reinstall the template:
```bash
dotnet new uninstall Clean.Architecture.Solution.Template
dotnet new install Clean.Architecture.Solution.Template::8.0.0-preview.5.5
```

Create a new solution:
```bash
dotnet new ca-sln -cf None -o TestApi
```

In my tests `./src/WebApi` is created and linked correctly to the solution.

Note that I did find bug (#902) that would cause a build failure for the Web API project. That bug is being fixed now.

Let me know if you are still encountering the issue.

**Comment by jasontaylordev** [comment] 2023-07-10 02:09
Close this issue, feel free to reach out if you are still experiencing this problem.

**Closed by jasontaylordev** 2023-07-10 02:09 UTC
